dict_err_code = {
    0 : "success"
    , 1 : "Server support post only"
    , 10 : "Upload failed"
    , 11 : "No file"
    , 20 : "user_name or password or verify code is incorrect"
    , 21 : "Token incorrect"
    , 30 : "Customer not found"
    , 31 : "Customer id not found"
    , 32 : "Customer name not set"
    , 33 : "Customer address not set"
    , 34 : "Customer longitude not set"
    , 35 : "Customer latitude not set"
    , 40 : "note not found"
    , 41 : "note id not found"
    , 42 : "note date not set"
    , 43 : "note address not set"
    , 44 : "note longitude not set"
    , 45 : "note latitude not set"
    , 46 : "limit or offset not set"
    , 50 : "alarm not found"
    , 51 : "alarm id not exists"
    , 52 : "alarm note id not set"
    , 53 : "alarm date id not set"
    , 54 : "alarm update_date id not set"
    , 60 : "group name not set"
    , 61 : "update date not set"
    , 70 : "leader id not set"
    , 71 : "leader id not found"
    , 72 : "avatar not set"
    , 73 : "show_name not set"
    , 74 : "you cannot set your member as your leader"
    , 1000 : "Unknow error"
    , 1024 : "Developing"
}
