dict_err_code = {
    0 : "success"
    , 1 : "Server support post only"
    , 10 : "Upload failed"
    , 11 : "No file"
    , 20 : "user_name or password or verify code is incorrect"
    , 21 : "Token incorrect"
    , 30 : "Customer not found"
    , 31 : "Customer id not found"
    , 40 : "note not found"
    , 41 : "note id not found"
    , 50 : "alarm not found"
    , 51 : "alarm id not exists"
    , 52 : "alarm note id not set"
    , 53 : "alarm date id not set"
    , 54 : "alarm update_date id not set"
    , 1000 : "Unknow error"
    , 1024 : "Developing"
}